### PR TITLE
Don't catch every exception.

### LINKED ISSUE #46: When the server can't connect to MySQL, it tells the user that their password is wrong
This is a bad user experience, because it seems like their password was incorrect, but the log shows the real error.

Instead it should throw a real exception.

The exception that should be thrown is BadGateway.

Steps to reproduce:

1. Start server
2. Turn off mysql
3. Try logging in
4. Look at the log.

The reason the real mysql exception gets turned into a "Incorrect Username or Password" is because _all_ exceptions are being caught in `/src/login/controller.ts`

### PR DESCRIPTION
**Pull request by juhangsin**
Fixes #46

### CODE REVIEW

File: src/login/controller.ts [hunk 1]
```diff
@@ -22,8 +23,13 @@ class LoginController extends Controller {
     try {
       user = await UserService.findByIdentity('mailto:' + ctx.request.body.username);
     } catch (err) {
-      log(EventType.loginFailed, ctx);
-      return this.redirectToLogin(ctx, 'Incorrect username or password');
+      console.log('hello world', err)
```
Comment (evert) [inline src/login/controller.ts]: Debug code -_-
